import type { Quest } from "./types";

export const QUESTS: Quest[] = [
  {
    id: "wallet-fundamentals",
    title: "What Is a Wallet?",
    emoji: "👛",
    description: "The first thing every Web3 user needs — and what it actually is.",
    category: "academy",
    difficulty: "beginner",
    xpReward: 100,
    skillReward: { research: 5, security: 3 },
    achievementId: "wallet-apprentice",
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "A wallet isn't a bank account",
        body: "A crypto wallet doesn't actually store your coins — it stores the keys that prove you control an address on the blockchain. The balances live on-chain; your wallet is just how you sign transactions for that address.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "What does a wallet actually store?",
        options: [
          { id: "a", label: "Your coins, physically" },
          { id: "b", label: "The keys that prove you control an address" },
          { id: "c", label: "A copy of the entire blockchain" },
        ],
        correctOptionId: "b",
        explanation: "Your balance lives on the blockchain itself. Your wallet holds the private key that lets you sign transactions from your address — lose the key, lose access, even though the funds are still technically \"there.\"",
      },
    ],
  },
  {
    id: "private-keys",
    title: "What Does a Private Key Do?",
    emoji: "🔑",
    description: "The single most important secret in Web3 — and the #1 way people get rekt.",
    category: "academy",
    difficulty: "beginner",
    xpReward: 100,
    skillReward: { security: 8 },
    achievementId: "wallet-apprentice",
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "One key, total control",
        body: "Your private key mathematically proves ownership of your address and lets you authorize transactions. Anyone who has it has full, irreversible control of everything at that address. There is no password reset.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "What does a private key allow you to do?",
        options: [
          { id: "a", label: "Sign transactions and prove ownership of your address" },
          { id: "b", label: "Recover your account if you forget your password" },
          { id: "c", label: "See other people's wallet balances" },
        ],
        correctOptionId: "a",
        explanation: "A private key signs transactions — that's it, but that's everything. There's no \"forgot password\" flow in Web3. Anyone who gets your key gets your funds, permanently.",
      },
    ],
  },
  {
    id: "transactions-and-gas",
    title: "Transactions & Gas",
    emoji: "⛽",
    description: "Why every on-chain action costs something, and who gets paid.",
    category: "academy",
    difficulty: "beginner",
    xpReward: 120,
    skillReward: { onchain: 6, research: 4 },
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "Nothing on-chain is free",
        body: "Every transaction has to be processed and permanently stored by the network's validators. Gas is the fee you pay for that computation — it scales with network demand and how much work your transaction requires.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "Why does gas exist?",
        options: [
          { id: "a", label: "It's a tax collected by the app you're using" },
          { id: "b", label: "It pays validators for processing and securing your transaction" },
          { id: "c", label: "It's a fee only paid on expensive trades" },
        ],
        correctOptionId: "b",
        explanation: "Gas compensates the network for computation and storage. On a fast chain like Monad it's typically tiny — but it's never zero, because processing your transaction is never free for the network.",
      },
    ],
  },
  {
    id: "tokens-101",
    title: "What Is a Token?",
    emoji: "🪙",
    description: "Coins, tokens, and the difference nobody explains clearly.",
    category: "academy",
    difficulty: "beginner",
    xpReward: 100,
    skillReward: { defi: 5, research: 4 },
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "Native coins vs. tokens",
        body: "A chain's native currency (like MON on Monad) pays gas and secures the network. A token is anything else built on top — issued by a smart contract, representing value, access, or ownership, but riding on the underlying chain's infrastructure.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "What's the key difference between a native coin and a token?",
        options: [
          { id: "a", label: "Tokens are always worth less" },
          { id: "b", label: "A native coin secures the chain itself; a token is issued by a smart contract on top of it" },
          { id: "c", label: "There's no real difference" },
        ],
        correctOptionId: "b",
        explanation: "The native coin (MON, ETH, etc.) is baked into the protocol and pays for gas. Tokens are created by smart contracts and can represent anything — a stablecoin, a governance vote, an in-game item.",
      },
    ],
  },
  {
    id: "smart-contracts-101",
    title: "What Is a Smart Contract?",
    emoji: "📜",
    description: "The code that actually runs DeFi, NFTs, and everything else.",
    category: "academy",
    difficulty: "beginner",
    xpReward: 120,
    skillReward: { onchain: 6, defi: 4 },
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "Code that runs itself",
        body: "A smart contract is a program deployed on-chain that executes exactly as written, with no central operator. Once deployed, its logic is public and (usually) immutable — which is powerful, and also why bugs in smart contracts are so expensive.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "What makes a smart contract different from a normal app's backend?",
        options: [
          { id: "a", label: "It runs on a server owned by the company" },
          { id: "b", label: "It executes on-chain, publicly, without a central operator who can change the rules quietly" },
          { id: "c", label: "It can be edited by the developer at any time with no trace" },
        ],
        correctOptionId: "b",
        explanation: "That's the trade-off at the heart of DeFi: no one can quietly change the rules on you — but you also can't call support if something goes wrong. Read before you sign.",
      },
    ],
  },
  {
    id: "liquidity-pools-101",
    title: "Liquidity Pools 101",
    emoji: "💧",
    description: "You deposit $1,000 into a pool. The price moves. What happens to your position?",
    category: "academy",
    difficulty: "intermediate",
    xpReward: 150,
    skillReward: { defi: 10 },
    achievementId: "defi-explorer",
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "Liquidity pools rebalance automatically",
        body: "A liquidity pool holds two assets and lets traders swap between them. As the price ratio shifts, the pool automatically sells the asset that's rising and buys the one that's falling to keep the pool balanced — earning you trading fees, but exposing you to impermanent loss.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "If one asset in your pool doubles in price, what happens to your position versus just holding both assets?",
        options: [
          { id: "a", label: "It's worth exactly the same either way" },
          { id: "b", label: "The pool automatically sold some of the rising asset, so you end up with less upside than just holding" },
          { id: "c", label: "You're guaranteed a bigger profit than holding" },
        ],
        correctOptionId: "b",
        explanation: "This is impermanent loss: the pool's rebalancing means you underperform simply holding both assets whenever their price ratio moves. Fees earned can offset it, but not always fully — you'll feel this directly in The Lab.",
      },
    ],
  },
  {
    id: "survive-the-market-crash",
    title: "Survive the Market Crash",
    emoji: "📊",
    description: "You have 10,000 virtual MON. The market just dropped 30%. What will you do?",
    category: "academy",
    difficulty: "intermediate",
    xpReward: 250,
    skillReward: { riskManagement: 12, trading: 4 },
    achievementId: "risk-manager",
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "Volatility is the job, not the emergency",
        body: "Every trader eventually watches a position drop hard. What separates a survivable drawdown from a rekt account isn't predicting the crash — it's having decided your reaction in advance.",
      },
      {
        id: "decision",
        type: "decision",
        prompt: "Your portfolio just dropped 30% in an hour. What do you do?",
        options: [
          {
            id: "sell-all",
            label: "Panic sell everything",
            outcome: "You lock in the full 30% loss. The market recovers most of the drop over the next few days — you sold the bottom. Panic-selling turns a temporary drawdown into a permanent one.",
          },
          {
            id: "hold",
            label: "Hold and do nothing",
            outcome: "You avoid locking in the loss, but you also had no plan going in — this time it worked out, but \"hope\" isn't a risk management strategy you can repeat.",
          },
          {
            id: "partial-trim",
            label: "Trim part of the position, keep a stop-loss on the rest",
            outcome: "You reduce risk without fully exiting, and you've defined your downside if it keeps falling. This is the closest thing to a repeatable risk-management process — not because it's always the most profitable, but because it's the one you can survive doing over and over.",
          },
        ],
      },
    ],
  },
  {
    id: "rug-pull-detection",
    title: "Spot the Rug Pull",
    emoji: "🚩",
    description: "A new token is pumping. Something about the tokenomics feels off. Can you spot it?",
    category: "academy",
    difficulty: "intermediate",
    xpReward: 150,
    skillReward: { security: 10, research: 5 },
    achievementId: "rug-pull-survivor",
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "Rug pulls hide in the unlock schedule",
        body: "The classic rug pull isn't a hack — it's a team that holds a huge share of supply with little or no lock-up, free to dump on buyers the moment liquidity is thick enough to sell into.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "A new token has 40% held by the team with no vesting or lock-up, and the contract owner can mint unlimited new supply. What's the biggest red flag here?",
        options: [
          { id: "a", label: "The token has a logo that looks generic" },
          { id: "b", label: "The team can dump a huge, unlocked share whenever they want — and mint infinitely more" },
          { id: "c", label: "The token launched on a testnet" },
        ],
        correctOptionId: "b",
        explanation: "Unlocked team allocations and unrestricted mint functions are the two biggest structural rug-pull risks. Always check vesting schedules and whether supply is capped before buying into a new token.",
      },
    ],
  },
  {
    id: "meet-monad",
    title: "Meet Monad",
    emoji: "⚡",
    description: "The chain this entire app runs on — what makes it different.",
    category: "academy",
    difficulty: "beginner",
    xpReward: 150,
    skillReward: { onchain: 8, research: 4 },
    achievementId: "monad-pioneer",
    steps: [
      {
        id: "lesson",
        type: "lesson",
        prompt: "A parallel EVM",
        body: "Monad is an EVM-compatible Layer 1 built for high throughput — it executes transactions in parallel instead of one at a time, while staying compatible with existing Ethereum tooling like wagmi, viem, and Foundry.",
      },
      {
        id: "quiz",
        type: "quiz",
        prompt: "Why does EVM compatibility matter for a chain like Monad?",
        options: [
          { id: "a", label: "It means existing Ethereum contracts, wallets, and tools mostly work without rewriting them" },
          { id: "b", label: "It has nothing to do with development — it's a marketing term" },
          { id: "c", label: "It means the chain runs slower than Ethereum" },
        ],
        correctOptionId: "a",
        explanation: "EVM compatibility is why the wallet you just connected, and every contract The Onboarding deploys, works with the exact same tools built for Ethereum — just on a chain designed for far higher throughput.",
      },
    ],
  },
];

export function getQuestById(id: string): Quest | undefined {
  return QUESTS.find((q) => q.id === id);
}
